CREATE TABLE [dbo].[Tags] (
    [ID] UNIQUEIDENTIFIER NOT NULL,
    [Label] NVARCHAR(64) NOT NULL,
    [UserID] UNIQUEIDENTIFIER NOT NULL
    CONSTRAINT [PK_Tags] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Tags_Users] FOREIGN KEY ([UserID]) REFERENCES [Users] ([ID])
)
